CREATE DATABASE RETAIL_ANALYTICS;
USE RETAIL_ANALYTICS;

CREATE TABLE DIM_CUSTOMER(
CUSTOMER_ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
GENDER VARCHAR(10) NOT NULL CHECK(GENDER IN ("MALE","FEMALE","OTHER")),
CITY VARCHAR(50) NOT NULL,
AGE_GROUP VARCHAR(10)
);

SELECT * FROM DIM_CUSTOMER;

CREATE TABLE DIM_PRODUCT(
PRODUCT_ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
BRAND VARCHAR(50),
PRICE DECIMAL(10,2) NOT NULL
);

SELECT * FROM DIM_PRODUCT;

CREATE TABLE DIM_STORE(
STORE_ID INT PRIMARY KEY,
STORE_NAME VARCHAR(100) NOT NULL,
CITY VARCHAR(50) NOT NULL,
REGION VARCHAR(50) NOT NULL
);

SELECT* FROM DIM_STORE;

CREATE TABLE DIM_DATE(
DATE_ID DATE PRIMARY KEY,
YEAR INT NOT NULL,
MONTH INT NOT NULL,
DAY INT NOT NULL,
WEEKDAY VARCHAR(50) NOT NULL
);

SELECT* FROM DIM_DATE;

CREATE TABLE DIM_PAYMENT_METHOD(
PAYMENT_METHOD_ID INT PRIMARY KEY,
METHOD_NAME VARCHAR(50) NOT NULL
);

SELECT* FROM DIM_PAYMENT_METHOD;

CREATE TABLE FACT_SALES(
SALE_ID INT PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
STORE_ID INT NOT NULL,
DATE_ID DATE NOT NULL,
PAYMENT_METHOD_ID INT NOT NULL,
QUANTITY INT NOT NULL CHECK(QUANTITY>0),
TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
FOREIGN KEY(CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID),
FOREIGN KEY(STORE_ID) REFERENCES DIM_STORE(STORE_ID),
FOREIGN KEY(DATE_ID) REFERENCES DIM_DATE(DATE_ID),
FOREIGN KEY(PAYMENT_METHOD_ID) REFERENCES DIM_PAYMENT_METHOD(PAYMENT_METHOD_ID)
);

SELECT* FROM FACT_SALES;